import { Game } from "./ulits/data";

export const imgBanner = [
    "https://i.pinimg.com/originals/c3/58/54/c358546f5a3fe92c0d543686809ce364.jpg",
    "https://i2.wp.com/2.bp.blogspot.com/-II2GV4teQVQ/Xjz8PO7f_aI/AAAAAAAAA_c/j9EuXjArb1Q_o_EdbJJBMybaQTiKu9ZggCK4BGAYYCw/s1600/Preview%2B1.jpg"
]
export const gameData: Game[] = [
    {
        id: 1,
        name: "The Legend of Zelda: Breath of the Wild",
        img: "https://example.com/zelda.jpg",
        brand: "Nintendo",
        favorite: true,
        new: false,
        slots: false,
        live: false,
        jackpots: false,
    },
    {
        id: 2,
        name: "Super Mario Odyssey",
        img: "https://example.com/mario.jpg",
        brand: "Nintendo",
        favorite: false,
        new: true,
        slots: false,
        live: false,
        jackpots: false,
    },
    {
        id: 3,
        name: "The Witcher 3: Wild Hunt",
        img: "https://example.com/witcher3.jpg",
        brand: "CD Projekt Red",
        favorite: false,
        new: false,
        slots: false,
        live: false,
        jackpots: false,
    },
    {
        id: 4,
        name: "Minecraft",
        img: "https://example.com/minecraft.jpg",
        brand: "Mojang",
        favorite: true,
        new: false,
        slots: false,
        live: true,
        jackpots: false,
    },
    {
        id: 5,
        name: "Minecraft Dungeons",
        img: "https://example.com/minecraftdungeons.jpg",
        brand: "Mojang",
        favorite: false,
        new: true,
        slots: false,
        live: false,
        jackpots: false,
    },
    {
        id: 6,
        name: "Minecraft Story Mode",
        img: "https://example.com/minecraftstorymode.jpg",
        brand: "Mojang",
        favorite: false,
        new: false,
        slots: false,
        live: false,
        jackpots: false,
    },
    {
        id: 7,
        name: "Fortnite",
        img: "https://example.com/fortnite.jpg",
        brand: "Epic Games",
        favorite: true,
        new: false,
        slots: false,
        live: true,
        jackpots: true,
    },
    {
        id: 8,
        name: "Call of Duty: Modern Warfare",
        img: "https://example.com/codmw.jpg",
        brand: "Activision",
        favorite: false,
        new: false,
        slots: false,
        live: false,
        jackpots: false,
    },
    {
        id: 9,
        name: "Overwatch",
        img: "https://example.com/overwatch.jpg",
        brand: "Blizzard Entertainment",
        favorite: false,
        new: false,
        slots: false,
        live: false,
        jackpots: false,
    },
    {
        id: 10,
        name: "Halo Infinite",
        img: "https://example.com/haloinfinite.jpg",
        brand: "343 Industries",
        favorite: false,
        new: true,
        slots: true,
        live: true,
        jackpots: false,
    },
];

